---
javascript:
    displayName: Javascript
    steps:
        - file: "client_app.js"
          highlight: "0-536"
        - file: "index.html"
          highlight: "33-70"
        - file: "index.html"
          highlight: "50-57"
        - file: "language.json"
          highlight: "1-271"
        - file: "index.html"
          highlight: "69"
        - file: "client_app.js"
          highlight: "22-27"
        - file: "client_app.js"
          highlight: "36-112"
        - file: "client_app.js"
          highlight: "36-47"
        - file: "client_app.js"
          highlight: "58-102"
        - file: "client_app.js"
          highlight: "104-112"        
        - file: "client_app.js"
          highlight: "145-249"
        - file: "client_app.js"
          highlight: "153-188"
        - file: "client_app.js"
          highlight: "133-143"
        - file: "client_app.js"
          highlight: "251-265"
        - file: "client_app.js"
          highlight: "272-287"
        - file: "client_app.js"
          highlight: "272-287"