---
javascript:
    displayName: Javascript
    steps:
        - file: "client_app.js"
          highlight: "0-488"
        - file: "index.html"
          highlight: "33-70"
        - file: "index.html"
          highlight: "50-57"
        - file: "language.json"
          highlight: "1-271"
        - file: "index.html"
          highlight: "69"
        - file: "client_app.js"
          highlight: "19-25"
        - file: "client_app.js"
          highlight: "36-108"
        - file: "client_app.js"
          highlight: "36-47"
        - file: "client_app.js"
          highlight: "54-94"
        - file: "client_app.js"
          highlight: "96-108"        
        - file: "client_app.js"
          highlight: "183-243"
        - file: "client_app.js"
          highlight: "146-181"
        - file: "client_app.js"
          highlight: "246-268"
        - file: "client_app.js"
          highlight: "270-284"
        - file: "client_app.js"
          highlight: "291-341"
        - file: "client_app.js"
          highlight: "291-341"